# This is a generated file. Not intended for manual editing.
services:
  discountcode.service:
    build:
      context: "/Users/lidia/Documents/Proiecte/discount-code-service-v3/src"
      dockerfile: "DiscountCode.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "discountcode.service:dev"
    ports:
    - "127.0.0.1:57004:57000"
    - "127.0.0.1:57204:57200"
    - "127.0.0.1:57404:57400"
    volumes:
    - "/Users/lidia/Documents/Proiecte/discount-code-service-v3/src/DiscountCode.Service:/app:rw"
    - "/Users/lidia/Documents/Proiecte/discount-code-service-v3/src:/src:rw"
    - "/Users/lidia/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/lidia/.local/share/JetBrains/RiderRemoteDebugger/2024.3EAP2/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider EAP.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/lidia/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_10_08_18_40_42:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
